- name: Copy Grafana Repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install Grafana
  ansible.builtin.dnf:
    name: grafana-enterprise
    state: installed

- name: Start Service Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    enabled: yes

# - name: Copy Grafana Dashboard File
#   ansible.builtin.copy:
#     src: grafana-expense.json
#     dest: /tmp/grafana-expense.json

# - name: Import Grafana Dashboard
#   community.grafana.grafana_dashboard:
#     grafana_url: hhtp://172.31.92.76:3000
#     grafana_api_key: {{ grafana_api_key}}
#     state: present
#     commit_messages: Updated by Ansible
#     overwrite: true
#     path: /tmp/grafana-expense.json