- name: Unarchive and Install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Prometheus Service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy Prometheus file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml

- name: Copy Alerts file
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/alerts.yml

- name: Start Service Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Wait For Prometheus Port
  ansible.builtin.shell: sleep ; netstat -lntp | grep 9090

# - name: Check Service Grafana
#   ansible.builtin.systemd:
#     name: grafana
#     state: started
#     enabled: yes
#   register: out
#   ignore_errors: true


- name: Install Grafana
  ansible.builtin.shell: yum install -y https://dl.grafana.com/enterprise/release/grafana-enterprise-11.2.0-1.x86_64.rpm
  # when: out.status.ActiveState != "active"

- name: Start Service Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  # when: out.status.ActiveState != "active"

# - name: Copy Grafana Dashboard File
#   ansible.builtin.copy:
#     src: grafana-expense.json
#     dest: /tmp/grafana-expense.json

# - name: Import Grafana Dashboard
#   community.grafana.grafana_dashboard:
#     grafana_url: hhtp://172.31.92.76:3000
#     grafana_api_key: {{ grafana_api_key}}
#     state: present
#     commit_messages: Updated by Ansible
#     overwrite: true
#     path: /tmp/grafana-expense.json


- name: Unarchive and Install Alert Manager
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{alert_manager}}/alertmanager-{{alert_manager}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Alert Manager file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager-{{alert_manager}}.linux-amd64/alertmanager.yml

- name: Copy Alert Manager Service
  ansible.builtin.template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Start Service Alert Manager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Wait For Alert Manager Port
  ansible.builtin.shell: sleep ; netstat -lntp | grep 9093
