- name: Copy Elastic Repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ElasticSearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start ElasticSearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: started
    enabled: yes
