- name: Set HostName
  ansible>builtin.shell: set-hostname elastic

- name: Copy Elastic Repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ElasticSearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start ElasticSearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Start Kibana
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: yes

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Nginx Conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started