- name: Unarchive and Install Alert Manager
  ansible.builtin.unarchive:
    src: https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
    dest: /etc/yum.repos.d/artifactory-rpms.repo
    remote_src: yes

- name: Install Java and Jfrog
  ansible.builtin.dnf:
    name:
      - jfrog-artifactory-oss
      - java-17-openjdk.x86_64
    state: installed

- name: Start Service Jfrog
  ansible.builtin.systemd:
    name: artifactory
    state: restarted
    enabled: yes