- name: Copy Artifactory Repo
  ansible.builtin.template:
    src: artifactory.repo
    dest: /etc/yum.repos.d/artifactory.repo

- name: Install Java and Jfrog
  ansible.builtin.dnf:
    name:
      - jfrog-artifactory-oss
      - java-17-openjdk.x86_64
    state: installed

- name: Start Service Jfrog
  ansible.builtin.systemd:
    name: artifactory
    state: restarted
    enabled: yes